export const leadsData = {
  leads: [
    {
      id: "1",
      name: "Liam Anderson",
      source: "Website",
      stage: "lead",
      plan: "Free",
      quality: "Warm",
      views: 0,
      messageCount: 0,
      timeAgo: "15m ago",
      activities: [
        {
          title: "Lead generated",
          subtitle: "Website",
          time: "11:45",
        },
        {
          title: "Client Called",
          time: "14:05",
        },
      ],
      messages: [],
      unreadMessages: 0,
    },
    {
      id: "2",
      name: "Sophia Martinez",
      source: "Google Ads",
      stage: "lead",
      plan: "Basic",
      quality: "Cold",
      views: 0,
      messageCount: 0,
      timeAgo: "22m ago",
      unreadMessages: 2,
      messages: [
        {
          content: "Hi, I'm interested in your services",
          time: "10:30 AM",
          isOutgoing: false,
        },
        {
          content: "Can you tell me more about your pricing?",
          time: "10:32 AM",
          isOutgoing: false,
        },
      ],
    },
    {
      id: "3",
      name: "Ethan Johnson",
      source: "Google Ads",
      stage: "lead",
      plan: "Premium",
      quality: "Hot",
      views: 0,
      messages: 0,
      timeAgo: "33m ago",
      unreadMessages: 0,
    },
    {
      id: "4",
      name: "Ava Thompson",
      source: "Meta Ads",
      stage: "lead",
      plan: "Enterprise",
      quality: "Warm",
      views: 0,
      messages: 0,
      timeAgo: "38m ago",
      unreadMessages: 0,
    },
    {
      id: "5",
      name: "Mia Wilson",
      source: "Email Campaign",
      stage: "lead",
      plan: "Basic",
      quality: "Cold",
      views: 0,
      messages: 0,
      timeAgo: "50m ago",
      unreadMessages: 0,
    },
    {
      id: "6",
      name: "Noah Thompson",
      source: "Website",
      stage: "called",
      plan: "Premium",
      quality: "Hot",
      isElite: true,
      rating: 4,
      views: 4,
      messages: 1,
      timeAgo: "3h ago",
      unreadMessages: 0,
    },
    {
      id: "7",
      name: "Aiden Carter",
      source: "Website",
      stage: "called",
      plan: "Basic",
      quality: "Warm",
      isElite: true,
      rating: 3,
      views: 4,
      messages: 1,
      timeAgo: "4h ago",
      unreadMessages: 0,
    },
    {
      id: "8",
      name: "Sophie Vergara",
      source: "Website",
      stage: "called",
      plan: "Free",
      quality: "Cold",
      isElite: true,
      rating: 2,
      views: 1,
      messages: 1,
      timeAgo: "13h ago",
      unreadMessages: 0,
    },
    {
      id: "9",
      name: "Name",
      source: "Website",
      stage: "trial",
      plan: "Premium",
      quality: "Hot",
      isElite: true,
      rating: 4,
      timeLeft: "2d",
      views: 4,
      messages: 3,
      unreadMessages: 0,
    },
    {
      id: "10",
      name: "Noah Thompson",
      source: "Website",
      stage: "subscribed",
      plan: "Enterprise",
      quality: "Hot",
      isElite: true,
      date: "3rd Mar 2024",
      views: 4,
      messages: 1,
      timeAgo: "3h ago",
      unreadMessages: 0,
    },
    {
      id: "11",
      name: "Aiden Carter",
      source: "Website",
      stage: "subscribed",
      plan: "Premium",
      quality: "Warm",
      isElite: true,
      date: "22nd Apr 2024",
      views: 4,
      messages: 1,
      timeAgo: "4h ago",
      unreadMessages: 0,
    },
    {
      id: "12",
      name: "Sophie Vergara",
      source: "Website",
      stage: "subscribed",
      plan: "Basic",
      quality: "Cold",
      isElite: true,
      date: "8th Jul 2024",
      views: 1,
      messages: 1,
      timeAgo: "13h ago",
      unreadMessages: 0,
    },
    {
      id: "13",
      name: "Name",
      source: "Website",
      stage: "onboarded",
      plan: "Enterprise",
      quality: "Hot",
      isElite: true,
      date: "15th Jan 2024",
      documents: 3,
      views: 4,
      messages: 1,
      timeAgo: "4d ago",
      unreadMessages: 0,
    },
    {
      id: "14",
      name: "Jim Carter",
      source: "Website",
      stage: "onboarded",
      plan: "Premium",
      quality: "Warm",
      isElite: true,
      date: "19th Sep 2024",
      views: 4,
      messages: 1,
      timeAgo: "4h ago",
      unreadMessages: 0,
    },
  ],
}

